site_name: RetroDocs-b1.7.3
site_url: https://trnrr.github.io/RetroDocs-b1.7.3
site_description: Community driven documentation for Minecraft Beta 1.7.3 Craftbukket plugins.
repo_name: Trnrr/RetroDocs-b1.7.3
repo_url: https://github.com/Trnrr/RetroDocs-b1.7.3
copyright: Maintained by Trnrr

##########################################################
nav:
- Home: index.md
- Setting up a Server.md
- ...
- 'Glass Repo': 'https://glass-repo.net'

##########################################################
theme:
  name: 'material'
  logo: assets/old-cobble.png
  icon:
    repo: fontawesome/brands/github
  features:
    - search.highlight
    - search.share
    - navigation.tracking
    - content.action.view
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      #scheme: default
      primary: green
      accent: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

##########################################################
plugins:
  - search:
      lang: en
  - awesome-pages #works

extra:
  status:
    new: Work in progress, expect changes.

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde